name: Check Environment and Packages

on:
  push:
  workflow_dispatch:

jobs:
  check:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"

    name: Check Environment and Packages on ${{ matrix.os }}

    steps:
      - name: Check
        run: |
          set +e
          set -x

          git --version
          gh --version
          jq --version
          xmllint -version

          sqlite3 --version

          php -v
          pear version

          set -e
