name: Actions Syntax Test

on: push

jobs:
  syntax:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - run: echo $GITHUB_REF

      - name: Multi-line commands
        run: |
          ./unsuccessful.sh
          echo "Next"

      - name: Next step
        run: echo "I am the next step"
