name: Actions Syntax Test

on: push

jobs:
  syntax:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: echo env
        run: |
          echo $GITHUB_REF
          echo $(basename $GITHUB_REF)

      # - name: Multi-line commands
      #   run: |
      #     ./unsuccessful.sh
      #     echo "Next"

      - name: Next step
        run: echo "I am the next step"

      - name: Check git command
        run: git clone git@github.com:laravel/docs.git laravel-docs
